version: "3.8"

services:

  java_app:
    image: swapnil2298/expenses-tracker-java_app:${IMAGE_TAG}
    container_name: "expenseapp"
    networks:
      - expense-app-nw
    ports:
      - "8080:8080"
    environment:
       SPRING.DATASOURCE.URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
       SPRING.DATASOURCE.USERNAME: "root" 
       SPRING.DATASOURCE.PASSWORD: "Test@123"
    depends_on:
      - mysql_db
    restart: always

  mysql_db:
    image: mysql
    container_name: "mysql"
    networks:
      - expense-app-nw
    environment:
      MYSQL_ROOT_PASSWORD: "Test@123"
      MYSQL_DATABASE: "expenses_tracker"
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s
    volumes:
      - ./java-app-data:/var/lib/mysql
    restart: always


networks:
  expense-app-nw:
